package i18n

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// serverTCallKeyPattern finds calls to the package's own T function,
// qualified as i18n.T from outside the package, with a server.* key as the
// second argument — the Go-side mirror of catalog_usage_test.go's
// tCallKeyPattern for app.js. Anchored on the "i18n." qualifier, never a
// bare call: Go generics name their type parameter T everywhere ([T any]),
// so an unqualified pattern would drown in false matches.
var serverTCallKeyPattern = regexp.MustCompile(`i18n\.T\(\s*[^,]+,\s*"(server\.[a-zA-Z0-9_.]+)"`)

// serverScanSkipDirs keeps the walk inside the one real tree: other
// worktrees are full duplicate copies of this same code (would double-count
// every call site, harmlessly, but also silently hide a rename that only
// happened in one copy), and the rest is tool state / build output, never
// Go source that ships.
var serverScanSkipDirs = map[string]bool{
	".git": true, ".claude": true, ".clevercoder": true, ".githooks": true,
	".impeccable": true, ".stash-tmp": true, "worktrees": true, "dist": true,
}

// TestServerKeysMatchGoCallSites is TestAllKeysMatchBetweenFrontendAndCatalog's
// sibling for the server.* universe that test deliberately excludes (T153
// etapa 3a, ct-2026-09-16-1803): text app.js never asks for because it
// never reaches the dashboard — WhatsApp/email notices generated by Go.
// Same two-way guarantee, Go side: every server.* catalog key is used by
// some i18n.T(...) call, and every key an i18n.T(...) call asks for exists
// in BOTH catalogs. Without this, the Go side has no guard at all and can
// desync in silence — exactly what this whole catalog exists to prevent.
func TestServerKeysMatchGoCallSites(t *testing.T) {
	used := map[string]bool{}
	root := "../.."
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if serverScanSkipDirs[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, m := range serverTCallKeyPattern.FindAllSubmatch(data, -1) {
			used[string(m[1])] = true
		}
		return nil
	})
	if err != nil {
		t.Fatalf("recorriendo %s: %v", root, err)
	}
	if len(used) == 0 {
		t.Fatal("ningún i18n.T(...) con clave server.* encontrado — el path o el regex están rotos, no el catálogo")
	}

	for k := range used {
		if _, ok := esCatalog[k]; !ok {
			t.Errorf("clave %q pedida por i18n.T(...) pero falta en esCatalog", k)
		}
		if _, ok := enCatalog[k]; !ok {
			t.Errorf("clave %q pedida por i18n.T(...) pero falta en enCatalog", k)
		}
	}
	for k := range esCatalog {
		if !strings.HasPrefix(k, "server.") {
			continue
		}
		if !used[k] {
			t.Errorf("clave %q existe en esCatalog pero ningún i18n.T(...) la pide", k)
		}
	}
}
